export const ADD_SCHOOLS_REQUEST = '@SCHOOL/ADD_SCHOOL_REQUEST';
export const ADD_SCHOOLS_SUCCESS = '@SCHOOL/ADD_SCHOOL_SUCCESS';
export const GET_SCHOOLS_REQUEST = '@SCHOOL/GET_SCHOOLS_REQUEST';
export const GET_SCHOOLS_SUCCESS = '@SCHOOL/GET_SCHOOLS_SUCCESS';
export const UPDATE_SCHOOLS_REQUEST = '@SCHOOL/UPDATE_SCHOOL_REQUEST';
export const UPDATE_SCHOOLS_SUCCESS = '@SCHOOL/UPDATE_SCHOOL_SUCCESS';
export const DELETE_SCHOOLS_REQUEST = '@SCHOOL/DELETE_SCHOOL_REQUEST';
export const DELETE_SCHOOLS_SUCCESS = '@SCHOOL/DELETE_SCHOOL_SUCCESS';
export const SEARCH_SCHOOLS_REQUEST = '@SCHOOL/SEARCH_SCHOOLS_REQUEST';
export const SEARCH_SCHOOLS_SUCCESS = '@SCHOOL/SEARCH_SCHOOLS_SUCCESS';
export const CLEAR_SCHOOLS = '@SCHOOL/CLEAR_SCHOOLS';
export const SCHOOLS_ERROR = '@SCHOOL/SCHOOLS_ERROR';

export const SET_CURRENT_REQUEST = '@current/SET_CURRENT_REQUEST';
export const SET_CURRENT_SUCCESS = '@current/SET_CURRENT_SUCCESS';
